// Search repositories
export const SEARCH_UPDATE = 'SEARCH_UPDATE';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const SEARCH_RESET = 'SEARCH_RESET';

// Fetch repositories
export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'
export const FETCH_REPOSITORIES_ERROR = 'FETCH_REPOSITORIES_ERROR'