// Search repositories
export const SEARCH_UPDATE = 'SEARCH_UPDATE';
export const SEARCH_SUBMIT = 'SEARCH_SUBMIT';
export const SEARCH_RESET = 'SEARCH_RESET';

// Fetch repositories
export const FETCH_REPOSITORIES = 'FETCH_REPOSITORIES'
export const FETCH_REPOSITORIES_SUCCESS = 'FETCH_REPOSITORIES_SUCCESS'
export const FETCH_REPOSITORIES_ERROR = 'FETCH_REPOSITORIES_ERROR'
export const RESET_REPOSITORIES = 'RESET_REPOSITORIES'

// Fetch contributors
export const FETCH_CONTRIBUTORS = 'FETCH_CONTRIBUTORS'
export const FETCH_CONTRIBUTORS_SUCCESS = 'FETCH_CONTRIBUTORS_SUCCESS'
export const FETCH_CONTRIBUTORS_ERROR = 'FETCH_CONTRIBUTORS_ERROR'
export const RESET_CONTRIBUTORS = 'RESET_CONTRIBUTORS'

// Utility actions
export const CONTRIBUTORS_PAGE_UP = 'CONTRIBUTORS_PAGE_UP'